import React, { useCallback, useEffect, useRef, useState } from "react";
import Icon from "./Icon";
import { Button, CopyButton } from "./ui";
import { apiJSON } from "../lib/api";

// One panel for every AI assistant (report summary, indicator triage, bulk digest, investigation write-up, mail
// explanation). The server gathers or receives the facts and returns {headline, summary, points, next_steps, caveats};
// this panel only ever shows that as plain text, labelled as AI-generated, with the data it came from left in place
// on the page around it.

let cache = { at: 0, value: null };
const FRESH_MS = 60 * 1000;

export function useAiStatus() {
  const [status, setStatus] = useState(Date.now() - cache.at < FRESH_MS ? cache.value : null);
  useEffect(() => {
    if (Date.now() - cache.at < FRESH_MS && cache.value) return undefined;
    let alive = true;
    apiJSON("/v2/ai/status")
      .then(v => { cache = { at: Date.now(), value: v }; if (alive) setStatus(v); })
      .catch(() => { if (alive) setStatus({ allowed: false, available: false }); });
    return () => { alive = false; };
  }, []);
  return status;
}

export function aiToMarkdown(title, r) {
  if (!r) return "";
  const list = items => (items || []).map(x => `- ${x}`).join("\n");
  return [`## ${title}`, r.headline && `**${r.headline}**`, r.summary, r.points?.length && `### What stands out\n${list(r.points)}`,
    r.next_steps?.length && `### Next steps\n${list(r.next_steps)}`, r.caveats?.length && `### Caveats\n${list(r.caveats)}`,
    "_AI-generated. Check it against the underlying data before acting on it._"].filter(Boolean).join("\n\n");
}

function Section({ title, items, tone }) {
  if (!items || !items.length) return null;
  return (
    <div className="ai-sec">
      <div className="ai-sec-t">{title}</div>
      <ul className={`ai-list ${tone || ""}`}>{items.map((x, i) => <li key={i}>{x}</li>)}</ul>
    </div>
  );
}

export function AiAnswer({ title, answer, onRegenerate, busy }) {
  const r = answer.result;
  return (
    <div className="ai-answer">
      {r.headline && <div className="ai-headline">{r.headline}</div>}
      {r.summary && <p className="ai-summary">{r.summary}</p>}
      <Section title="What stands out" items={r.points} />
      <Section title="Next steps" items={r.next_steps} tone="steps" />
      <Section title="Caveats" items={r.caveats} tone="caveats" />
      <div className="ai-foot">
        <span className="faint xs">AI-generated by {answer.provider}{answer.model ? ` · ${answer.model}` : ""}{answer.usage?.total_tokens ? ` · ${answer.usage.total_tokens.toLocaleString()} tokens` : ""}. Check it against the data before acting on it.</span>
        <span className="row" style={{ gap: 6 }}>
          <CopyButton value={aiToMarkdown(title, r)} />
          {onRegenerate && <Button size="sm" variant="ghost" icon="refresh" onClick={onRegenerate} loading={busy}>Regenerate</Button>}
        </span>
      </div>
    </div>
  );
}

export default function AiPanel({ title = "AI summary", cta = "Summarize", hint, path, body, ready = true, disabledHint, onAnswer, className = "" }) {
  const status = useAiStatus();
  const [phase, setPhase] = useState("idle");
  const [answer, setAnswer] = useState(null);
  const [error, setError] = useState(null);
  const key = JSON.stringify(body || null);
  const lastKey = useRef(key);

  // A different subject (another report selection, another investigation) invalidates the old answer.
  useEffect(() => {
    if (lastKey.current !== key) { lastKey.current = key; setPhase("idle"); setAnswer(null); setError(null); }
  }, [key]);

  const run = useCallback(async () => {
    setPhase("loading"); setError(null);
    try {
      const out = await apiJSON(path, { method: "POST", body });
      setAnswer(out); setPhase("done");
      if (onAnswer) onAnswer(out);
    } catch (e) {
      setError(e); setPhase(answer ? "done" : "error");
    }
  }, [path, body, onAnswer, answer]);

  if (!status || !status.allowed) return null;
  if (!status.available) {
    return (
      <div className={`ai-panel off ${className}`}>
        <span className="ai-ico"><Icon name="sparkle" size={16} /></span>
        <div className="ai-text">
          <div className="ai-title">{title}</div>
          <div className="faint small">Turn this on by adding a Groq or CodeCraft key.</div>
        </div>
        <Button size="sm" onClick={() => window.dispatchEvent(new Event("tf:keys"))}>Add a key</Button>
      </div>
    );
  }
  return (
    <div className={`ai-panel ${phase === "done" ? "done" : ""} ${className}`}>
      <div className="ai-head">
        <span className="ai-ico"><Icon name="sparkle" size={16} /></span>
        <div className="ai-text">
          <div className="ai-title">{title}<span className="ai-tag">AI</span></div>
          {phase !== "done" && <div className="faint small">{ready ? hint : (disabledHint || hint)}</div>}
        </div>
        {phase === "idle" || phase === "error" ? (
          <Button size="sm" variant="primary" icon="sparkle" onClick={run} disabled={!ready}>{cta}</Button>
        ) : null}
      </div>
      {phase === "loading" && !answer && (
        <div className="ai-loading" aria-live="polite">
          <div className="skel" style={{ width: "62%" }} /><div className="skel" style={{ width: "92%" }} /><div className="skel" style={{ width: "78%" }} />
          <span className="faint xs">Reading the data…</span>
        </div>
      )}
      {error && (
        <div className="ai-error" role="alert">
          {error.message}
          {error.status === 503 && <> <button className="linkish" onClick={() => window.dispatchEvent(new Event("tf:keys"))}>Add a key</button></>}
        </div>
      )}
      {answer && <AiAnswer title={title} answer={answer} onRegenerate={run} busy={phase === "loading"} />}
    </div>
  );
}
